// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB7r5Vd7-NZTcZAovr4D26zKksKdH6R8k',
    appId: '1:987546674175:web:f13ef6e1e99fe329773dca',
    messagingSenderId: '987546674175',
    projectId: 'flutterfire-ui-codelab-1ffe1',
    authDomain: 'flutterfire-ui-codelab-1ffe1.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-1ffe1.firebasestorage.app',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFqMpm_qGCnsxswikrBKc0WGZKiTPV6c',
    appId: '1:987546674175:android:847b85c8c7a9d189773dca',
    messagingSenderId: '987546674175',
    projectId: 'flutterfire-ui-codelab-1ffe1',
    storageBucket: 'flutterfire-ui-codelab-1ffe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApnwSL6PxAe1vE_Jwvh8VZfp6KeTdsgl8',
    appId: '1:987546674175:ios:c46bb0a24dce0de0773dca',
    messagingSenderId: '987546674175',
    projectId: 'flutterfire-ui-codelab-1ffe1',
    storageBucket: 'flutterfire-ui-codelab-1ffe1.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApnwSL6PxAe1vE_Jwvh8VZfp6KeTdsgl8',
    appId: '1:987546674175:ios:c46bb0a24dce0de0773dca',
    messagingSenderId: '987546674175',
    projectId: 'flutterfire-ui-codelab-1ffe1',
    storageBucket: 'flutterfire-ui-codelab-1ffe1.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

}